### ISSUE TITLE
Error: Specified images.domains should be an Array of strings received invalid values ().

### ISSUE THREAD

**Issue by ktjd123** [ChoJongHoon/develofolio#7]
Checkout https://nextjs.org/docs/messages/invalid-images-config

```js
	images: {
		domains: [
			process.env.NEXT_PUBLIC_RESOURCE_DOMAIN,
			'avatars.githubusercontent.com',
		],
	},
```

the line `process.env.NEXT_PUBLIC_RESOURCE_DOMAIN,` is giving error.

I think this line gives error since there is no 'NEXT_PUBLIC_RESOURCE_DOMAIN' env.

**Comment by ChoJongHoon** [comment]
관심가져주셔서 감사합니다. 환경변수 `.env` 파일이 없어서 발생하는 문제인걸로 보여요~
베타 버전 릴리즈 이후 컨트리뷰트 가이드 문서를 작성해놓겠습니다.
