### ISSUE TITLE
프로잭트 빌드 시 에러 - NEXT_PUBLIC_IMAGES_HOST

### ISSUE THREAD

**Issue by gyoon-dev** [ChoJongHoon/develofolio#71]
오랜만에 프로잭트를 실행하려는데
(예전에 약속했던 PR 을 하나 올려보력요 ㅎ)
`yarn && yarn dev` 를 하면 에러가 납니다 ;;

> packages/client/next.config.js:25:40

**TypeError: Cannot read property 'replace' of undefined** 
`process.env.NEXT_PUBLIC_IMAGES_HOST.replace(/(^\w+:|^)\/\//, ''),`

NEXT_PUBLIC_IMAGES_HOST 를 받아서 제쪽에 env.local 에 추가해서 실행하면 되나요?

**Comment by ChoJongHoon** [comment]
컨트리뷰트 가이드 작성을 계속 미루고 있었네요. 😅 이번주 내로 빠르게 작성해보겠습니다.
참고로 로컬에서 실행하기 위해 `.env`파일과 PostgreSQL 설치가 필요합니다!

참고: #7

**Comment by ChoJongHoon** [comment]
@gyoon-dev 

https://github.com/ChoJongHoon/develofolio/blob/main/CONTRIBUTING.md

디벨로폴리오에 기여하기위한 가이드 문서를 작성했습니다.

**Comment by gyoon-dev** [comment]
CONTRIBUTING.md 가이드대로 하니
postgres server 까지 잘 생성되어서 localhost 에서 사이트 잘 띄워지네요.

간단한 PR 하나 생성하려는데 push 가 안되네요 (제쪽 문제 입니다).
또 시간 내어서 곧 PR 올려보겠습니다.

develofolio 역시 점점 멋지게 발전하고 있네요 👏
