### ISSUE TITLE
Github 로그인이 불가하여 회원탈퇴를 하지 못하고 있습니다.

### ISSUE THREAD

**Issue by TERADA-DANTE** [ChoJongHoon/develofolio#89]
포트폴리오 내용에 법적인 수정이 필요한 부분이 있어 본인의 포트폴리오를 수정하려고 하는데, 
로그인을 할 수 없어, 수정이 불가능 한 상황입니다.
https://matsunaga.develofolio.com/의 내용을 삭제하고 싶습니다.

**Comment by TERADA-DANTE** [comment]
Github로 로그인 한 상태입니다.

**Comment by ChoJongHoon** [comment]
최근 API 주소를 변경하면서 깃허브 OAuth 설정을 같이 변경해주지 않았던 것이 문제였고 수정하였습니다. 감사합니다.
